name: GitHub Classroom Autograding
on: [push]
jobs:
  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autograding
        id: autograding
        uses: education/autograding-command-grader@v1
        with:
          test-name: autograding
          setup-command: npm install
          command: npm test
          timeout: 10
          max-score: 100
      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          AUTOGRADING_RESULTS: "${{steps.autograding.outputs.result}}"
        with:
          runners: autograding
